perfsonar-toolkit-systemenv: update logging setup

diff --git a/debian/patches/debian-systemenv.diff b/debian/patches/debian-systemenv.diff
--- a/debian/patches/debian-systemenv.diff
+++ b/debian/patches/debian-systemenv.diff
@@ -187,3 +187,37 @@
 +  sed -i '/^[[:space:]]*<\/VirtualHost>/i \
 +		SSLCipherSuite' $SSLCONF
 +sed -i 's|SSLCipherSuite.*|SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA|g' $SSLCONF
+--- a/scripts/system_environment/configure_syslog_local5_location
++++ b/scripts/system_environment/configure_syslog_local5_location
+@@ -8,27 +8,21 @@
+ # Set 'local5' output location to /var/log/perfsonar/owamp_bwctl.log
+ grep ^local5 /etc/rsyslog.d/owamp_bwctl-syslog.conf &> /dev/null
+ if [ $? != 0 ]; then
+-cat >> /etc/rsyslog.d/owamp_bwctl-syslog.conf <<EOF                                          
++cat >> /etc/rsyslog.d/owamp_bwctl-syslog.conf <<EOF
+ # Save bwctl and owamp messages to /var/log/perfsonar/owamp_bwctl.log
+ local5.*                                                -/var/log/perfsonar/owamp_bwctl.log
++& stop
+ EOF
+ fi
+ 
+-# Disable sync on /var/log/messages to save IO
+-sed 's/ \/var\/log\/messages/ -\/var\/log\/messages/g' /etc/rsyslog.conf > /etc/rsyslog.conf.tmp
+-# Cleanup any incorrect --/var/log/messages entries from earlier versions
+-sed -i 's/--*\/var\/log\/messages/-\/var\/log\/messages/g' /etc/rsyslog.conf.tmp
+-mv /etc/rsyslog.conf.tmp /etc/rsyslog.conf
+-
+ # Make sure that the owamp/bwctl log file gets rotated regularly
+ grep owamp_bwctl.log /etc/logrotate.d/syslog &> /dev/null
+ if [ $? != 0 ]; then
+-cat >>/etc/logrotate.d/syslog <<EOF
++cat >>/etc/logrotate.d/perfsonar-toolkit <<EOF
+ /var/log/perfsonar/owamp_bwctl.log {
+     sharedscripts
+     postrotate
+-        /bin/kill -HUP \`cat /var/run/syslogd.pid 2> /dev/null\` 2> /dev/null || true
+-        /bin/kill -HUP \`cat /var/run/rsyslogd.pid 2> /dev/null\` 2> /dev/null || true
++        invoke-rc.d rsyslog rotate > /dev/null
+     endscript
+ }
+ EOF
