Re-working the way the esmond db gets setup

diff --git a/scripts/system_environment/configure_esmond b/scripts/system_environment/configure_esmond
--- a/scripts/system_environment/configure_esmond
+++ b/scripts/system_environment/configure_esmond
@@ -27,6 +27,21 @@ if [ $? -ne 0 ]; then
     sed -i "s/sql_db_name = .*/sql_db_name = esmond/g" /etc/esmond/esmond.conf
     sed -i "s/sql_db_user = .*/sql_db_user = esmond/g" /etc/esmond/esmond.conf
     sed -i "s/sql_db_password = .*/sql_db_password = 7hc4m1/g" /etc/esmond/esmond.conf
+    drop-in -n -t esmond - ${PG_DATADIR}/pg_hba.conf <<EOF
+#
+# esmond
+#
+# This user should never need to access the database from anywhere
+# other than locally.
+#
+local     esmond          esmond                            md5
+host      esmond          esmond     127.0.0.1/32           md5
+host      esmond          esmond     ::1/128                md5
+EOF
+    /sbin/service ${PG_SERVICE_NAME} restart 
+    if [ $? -ne 0 ]; then
+        echo "Unable to start ${PG_SERVICE_NAME}. Your esmond database may not be initialized"
+    fi
 fi
 
 #disable JMX in cassandra so will start even if /etc/sysconfig/network HOSTNAME does not resolve
