Initail commit of pscheduler packaging prep

diff --git a/scripts/system_environment/configure_esmond b/scripts/system_environment/configure_esmond
--- a/scripts/system_environment/configure_esmond
+++ b/scripts/system_environment/configure_esmond
@@ -1,23 +1,33 @@
 #!/bin/bash
+PG_VERSION=9.5
+PG_BINDIR=/usr/pgsql-${PG_VERSION}/bin
+PG_DATADIR=/var/lib/pgsql/${PG_VERSION}/data
+PG_SERVICE_NAME="postgresql-${PG_VERSION}"
 
-#init postgres
-if [ -z "$(ls -A /var/lib/pgsql/data)" ]; then
-    /sbin/service postgresql initdb
-    /sbin/service postgresql start
-    echo "Waiting for postgresql to complete startup"
-    sleep 20
-    sudo -u postgres psql -c "CREATE USER esmond WITH PASSWORD '7hc4m1'"
-    sudo -u postgres psql -c "CREATE DATABASE esmond"
-    sudo -u postgres psql -c "GRANT ALL ON DATABASE esmond to esmond"
-    cp -f /etc/perfsonar/toolkit/default_service_configs/pg_hba.conf /var/lib/pgsql/data/pg_hba.conf
-    /sbin/service postgresql restart
+#init postgres - we shouldn't ever have to do this
+if [ -z "$(ls -A ${PG_DATADIR})" ]; then
+    su -l postgres -c "${NEW_BINDIR}/initdb  --locale='C' --encoding='sql_ascii' --pgdata='${PG_DATADIR}' --auth='trust'"
+fi
+
+#make sure postgresql is running
+/sbin/service ${PG_SERVICE_NAME} status &> /dev/null
+if [ $? -ne 0 ]; then
+    /sbin/service ${PG_SERVICE_NAME} restart 
+    if [ $? -ne 0 ]; then
+        echo "Unable to start ${PG_SERVICE_NAME}. Your esmond database may not be initialized"
+    fi
+fi
+
+#create user  if auth fails
+psql -U esmond -c "\c esmond" &> /dev/null
+if [ $? -ne 0 ]; then
+    psql -U postgres -c "CREATE USER esmond WITH PASSWORD '7hc4m1'" &> /dev/null
+    psql -U postgres -c "CREATE DATABASE esmond" &> /dev/null
+    psql -U postgres -c "GRANT ALL ON DATABASE esmond to esmond" &> /dev/null
     sed -i "s/sql_db_name = .*/sql_db_name = esmond/g" /etc/esmond/esmond.conf
     sed -i "s/sql_db_user = .*/sql_db_user = esmond/g" /etc/esmond/esmond.conf
     sed -i "s/sql_db_password = .*/sql_db_password = 7hc4m1/g" /etc/esmond/esmond.conf
 fi
-
-#install esmond config
-cp -f /etc/perfsonar/toolkit/default_service_configs/pg_hba.conf /var/lib/pgsql/data/pg_hba.conf
 
 #disable JMX in cassandra so will start even if /etc/sysconfig/network HOSTNAME does not resolve
 sed -i '/^JVM_OPTS="\$JVM_OPTS -Dcom.sun.management.jmx/ s/^/#/' /etc/cassandra/conf/cassandra-env.sh
@@ -40,3 +50,5 @@ python esmond/manage.py syncdb --noinput &> /dev/null
 
 #create api key
 KEY=`python esmond/manage.py add_api_key_user perfsonar 2> /dev/null | grep "Key:" | cut -f2 -d " "`
+
+#TODO: Switch on md5 auth
