Update the firewall scripts to put all the firewall changes into a 'perfSONAR' chain instead of overwriting the firewall rules each time

diff --git a/scripts/system_environment/configure_firewall b/scripts/system_environment/configure_firewall
--- a/scripts/system_environment/configure_firewall
+++ b/scripts/system_environment/configure_firewall
@@ -1,75 +1,155 @@
 #!/bin/bash
 
-#backup old versions
-if [ -f /etc/sysconfig/iptables ]; then
-    grep "perfSONAR Toolkit Firewall Config v1.1" /etc/sysconfig/iptables &> /dev/null
-    if [ $? != 0 ]; then
-       FILE_NUM=0
-       while [ -f "/etc/sysconfig/iptables.bak.${FILE_NUM}" ]; do
-           let FILE_NUM=FILE_NUM+1
-        done
+IS_UPGRADE=$1
 
-        mv /etc/sysconfig/iptables /etc/sysconfig/iptables.bak.${FILE_NUM}
-    fi
-fi
-if [ -f /etc/sysconfig/ip6tables ]; then
-    grep "perfSONAR Toolkit Firewall Config v1.1" /etc/sysconfig/ip6tables &> /dev/null
-    if [ $? != 0 ]; then
-       FILE_NUM=0
-       while [ -f "/etc/sysconfig/ip6tables.bak.${FILE_NUM}" ]; do
-           let FILE_NUM=FILE_NUM+1
-        done
-
-        mv /etc/sysconfig/ip6tables /etc/sysconfig/ip6tables.bak.${FILE_NUM}
-    fi
-fi
-
-#Insert new rules
-cp /opt/perfsonar_ps/toolkit/etc/firewall.conf /etc/sysconfig/iptables
-cp /opt/perfsonar_ps/toolkit/etc/firewall_v6.conf /etc/sysconfig/ip6tables
+CHAIN=perfSONAR
 
 #Determine BWCTL and OWAMP ports
-bwctlparams=("iperf_port" "nuttcp_port" "peer_port")
-bwctldefaults=("5001:5300" "5301-5600" "6001:6200")
+BWCTLPARAMS=("iperf_port" "nuttcp_port" "peer_port")
+BWCTLDEFAULTS=("5001:5300" "5301:5600" "6001:6200")
+OWAMPPARAMS=("testports")
+OWAMPDEFAULTS=("8760:9960")
 
-owampparams=("testports")
-owampdefaults=("8760:9960")
+BWCTLFILE="/etc/bwctld/bwctld.conf"
+OWAMPFILE="/etc/owampd/owampd.conf"
+FIREWALL_RULES="/opt/perfsonar_ps/toolkit/etc/firewall.conf"
+OLD_FIREWALL_RULES="/opt/perfsonar_ps/toolkit/etc/old_firewall_rules.conf"
 
-bwctlfile="/etc/bwctld/bwctld.conf"
-owampfile="/etc/owampd/owampd.conf"
+if [ ! -f $FIREWALL_RULES ]; then
+    echo "Couldn't find firewall rules"
+    exit -1
+fi
+
+main() {
+    if [ "${IS_UPGRADE}" == "upgrade" ]; then
+        echo "Deleting old firewall rules"
+        deleteOldFirewallRules
+    fi
+
+    echo "Adding perfSONAR firewall rules"
+    addFirewallRules
+
+    saveFirewallRules
+}
+
+saveFirewallRules() {
+    for iptables_cmd in "iptables" "ip6tables"; do
+        service $iptables_cmd save
+    done
+}
+
+deleteOldFirewallRules(){
+    for iptables_cmd in "iptables" "ip6tables"; do
+        readarray firewall_rules < ${OLD_FIREWALL_RULES}
+        for rule in "${firewall_rules[@]}"; do
+            case ${rule} in
+                "-D INPUT"*)
+                    echo $iptables_cmd $rule
+                    $iptables_cmd $rule &> /dev/null
+                    ;;
+            esac
+        done
+
+        p=`echo ${BWCTLPARAMS[@]}`;
+        deletePortRuleFromFile "$iptables_cmd" "$BWCTLFILE" "$p";
+        p=`echo ${OWAMPPARAMS[@]}`;
+        deletePortRuleFromFile "$iptables_cmd" "$OWAMPFILE" "$p";
+
+    done
+}
+
+addFirewallRules(){
+    for iptables_cmd in "iptables" "ip6tables"; do
+        # Create the chain if it doesn't currently exit
+        $iptables_cmd -n -L $CHAIN &> /dev/null
+        if [ $? != 0 ]; then
+            $iptables_cmd -N $CHAIN
+            if [ $? != 0 ]; then
+                echo "Problem createing firewall chain";
+                exit -1;
+            fi
+        fi
+
+        $iptables_cmd -F $CHAIN
+        if [ $? != 0 ]; then
+            echo "Problem removing existing firewall rules";
+            exit -1;
+        fi
+
+        readarray firewall_rules < ${FIREWALL_RULES}
+        for rule in "${firewall_rules[@]}"; do
+            case ${rule} in
+                "-A ${CHAIN}"*)
+                    $iptables_cmd $rule &> /dev/null
+                    ;;
+                "-I ${CHAIN}"*)
+                    $iptables_cmd $rule &> /dev/null
+                    ;;
+            esac
+        done
+
+        p=`echo ${BWCTLPARAMS[@]}`;
+        d=`echo ${BWCTLDEFAULTS[@]}`
+        addPortRuleFromFile "$iptables_cmd" "$BWCTLFILE" "$p" "$d";
+        p=`echo ${OWAMPPARAMS[@]}`;
+        d=`echo ${OWAMPDEFAULTS[@]}`
+        addPortRuleFromFile "$iptables_cmd" "$OWAMPFILE" "$p" "$d";
+
+        # Add a rule at the end to jump us back to the main process chain
+        $iptables_cmd -A ${CHAIN} -j RETURN
+
+        # Make sure that there's an INPUT rule to point us into the 
+        $iptables_cmd -n -L INPUT | grep -q "${CHAIN}[ \t]"
+        if [ $? != 0 ]; then
+            echo "Couldn't find chain"
+            $iptables_cmd -I INPUT -j ${CHAIN}
+        fi
+    done
+}
 
 addPortRuleFromFile(){
-	file=$1
-	local params=( `echo "$2"` )
-	local defaults=( `echo "$3"` )
-	
+	iptables_cmd=$1
+	file=$2
+	local params=( `echo "$3"` )
+	local defaults=( `echo "$4"` )
+
 	total=${#params[*]}
 	for (( i=0; i<=$(( $total - 1 )); i++ ))
 	do
-	    param_name="${params[$i]}"
-	    param_default="${defaults[$i]}"
+		param_name="${params[$i]}"
+		param_default="${defaults[$i]}"
+		portrange=`awk -v search="^$i" '$0 !~ /^#/ && $0 ~ search {$1=""; print $0}' $file | sed s/-/:/g`
 
-	    portrange=`awk -v search="^$param_name" '$0 !~ /^#/ && $0 ~ search {$1=""; print $0}' $file | sed s/-/:/g`
-	    if [ -z "$portrange" ]; then
-		portrange=$param_default
-		echo "Unable to find definition for \"$param_name\" in \"$file\", using default of \"$portrange\""
-	    fi
-	    if [ ! -z "$portrange" ]; then
-		echo "-I INPUT 1 -m udp -p udp --dport $portrange -j ACCEPT" >> /etc/sysconfig/iptables 
-		echo "-I INPUT 1 -m state --state NEW,ESTABLISHED -m tcp -p tcp --dport $portrange -j ACCEPT" >> /etc/sysconfig/iptables 
-		echo "-I INPUT 1 -m udp -p udp --dport $portrange -j ACCEPT" >> /etc/sysconfig/ip6tables
-		echo "-I INPUT 1 -m state --state NEW,ESTABLISHED -m tcp -p tcp --dport $portrange -j ACCEPT" >> /etc/sysconfig/ip6tables
-	    fi
-		
+		if [ -z "$portrange" ]; then
+			portrange=$param_default
+			echo "Unable to find definition for \"$param_name\" in \"$file\", using default of \"$portrange\""
+		fi
+
+		if [ ! -z "$portrange" ]; then
+			$iptables_cmd -A $CHAIN -m udp -p udp --dport $portrange -j ACCEPT
+			$iptables_cmd -A $CHAIN -m state --state NEW,ESTABLISHED -m tcp -p tcp --dport $portrange -j ACCEPT
+			$iptables_cmd -A $CHAIN -m udp -p udp --dport $portrange -j ACCEPT
+			$iptables_cmd -A $CHAIN -m state --state NEW,ESTABLISHED -m tcp -p tcp --dport $portrange -j ACCEPT
+		fi
 	done 
 }
 
-p=`echo ${bwctlparams[@]}`
-d=`echo ${bwctldefaults[@]}`
-addPortRuleFromFile "$bwctlfile" "$p" "$d"
-p=`echo ${owampparams[@]}`
-d=`echo ${owampdefaults[@]}`
-addPortRuleFromFile "$owampfile" "$p" "$d"
-echo "COMMIT" >> /etc/sysconfig/iptables
-echo "COMMIT" >> /etc/sysconfig/ip6tables
+deletePortRuleFromFile(){
+	iptables_cmd=$1
+	file=$2
+	local params=( `echo "$3"` )
+	for i in "${params[@]}"
+	do
+		portrange=`awk -v search="^$i" '$0 !~ /^#/ && $0 ~ search {$1=""; print $0}' $file | sed s/-/:/g`
+		if [ ! -z "$portrange" ]; then
+			$iptables_cmd -D INPUT -m udp -p udp --dport $portrange -j ACCEPT &> /dev/null
+			$iptables_cmd -D INPUT -m state --state NEW,ESTABLISHED -m tcp -p tcp --dport $portrange -j ACCEPT &> /dev/null
+			$iptables_cmd -D INPUT -m udp -p udp --dport $portrange -j ACCEPT &> /dev/null
+			$iptables_cmd -D INPUT -m state --state NEW,ESTABLISHED -m tcp -p tcp --dport $portrange -j ACCEPT &> /dev/null
+		fi
+	done 
+}
 
+main
+
+exit 0
